include $(GOROOT)/src/Make.inc

TARG=braldop/bra
GOFILES=\
	Point.go\
	Braldun.go\
	CompteBraldop.go\
	Communaute.go\
	LieuVille.go\
	Ville.go\
	Region.go\
	Carte.go\
	Couche.go\
	MemMap.go\
	MemCouche.go\
	VueBosquet.go\
	VueCadavre.go\
	VueChamp.go\
	VueCrevasse.go\
	VueEchoppe.go\
	VueEnvironnement.go\
	VueLieu.go\
	VueMonstre.go\
	VueObjet.go\
	VuePalissade.go\
	VuePosition.go\
	VueRoute.go\
	Vue.go\
	pngCouche.go\
	store.go\
	store_comptes.go\

include $(GOROOT)/src/Make.pkg
