include $(GOROOT)/src/Make.inc

TARG=mapper
GOFILES=\
	main/Point.go\
	main/VueChamp.go\
	main/VueEchoppe.go\
	main/VueEnvironnement.go\
	main/VuePosition.go\
	main/VueRoute.go\
	main/VueObjet.go\
	main/Braldun.go\
	main/LieuVille.go\
	main/Ville.go\
	main/Region.go\
	main/Map.go\
	main/Vue.go\
	main/MemMap.go\
	main/lectureScriptDynamique.go\
	main/lectureScriptStatique.go\
	main/LecteurScripts.go\

include $(GOROOT)/src/Make.cmd
