include $(GOROOT)/src/Make.inc

TARG=mapper
GOFILES=\
	main/Point.go\
	main/VueBosquet.go\
	main/VueCadavre.go\
	main/VueChamp.go\
	main/VueEchoppe.go\
	main/VueEnvironnement.go\
	main/VueMonstre.go\
	main/VueObjet.go\
	main/VuePalissade.go\
	main/VuePosition.go\
	main/VueRoute.go\
	main/Braldun.go\
	main/Communaute.go\
	main/LieuVille.go\
	main/Ville.go\
	main/Region.go\
	main/Carte.go\
	main/Couche.go\
	main/Vue.go\
	main/MemMap.go\
	main/MemCouche.go\
	main/lectureScriptDynamique.go\
	main/lectureScriptStatique.go\
	main/LecteurScripts.go\

include $(GOROOT)/src/Make.cmd
